def show_menu():
    print("\nChoose a visualization:")
    print("1. Age Distribution")
    print("2. BMI Distribution")
    print("3. Sleep Hours Distribution")
    print("4. Correlation Heatmap")
    print("5. BMI by Gender")
    print("6. Daily Steps vs BMI")
    print("7. Pairplot of Numeric Features")
    print("8. Daily steps vs BMI by Gender")
    print("9. BMI vs Age with Regression Line")
    print("10. Alcohol Consumption vs Heart Rate")
    print("11. Exercise Hours per Week by Smoker Status")
    print("12. Quit")